name: Convert Markdown to HTML

on:
  push:
    paths:
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Git-Repository klonen ohne externe Action
      - name: Checkout Repository
        run: |
          git clone https://github.com/captainhook23/captainhook23.github.io.git .
      
      # Schritt 2: Pandoc installieren
      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      # Schritt 3: README.md in index.html konvertieren
      - name: Convert README.md to test.html
        run: pandoc README.md -o test.html

      # Schritt 4: Änderungen commiten und pushen
      - name: Commit and push changes
        run: |
          git config --global user.name "Sven Lussmann"
          git config --global user.email "sven.lussmann@gmail.com"
          git add test.html
          git commit -m "Automated update of test.html"
          git push
