name: Convert Markdown to HTML

# Auslöser definieren (z. B. bei jedem Commit auf main oder wenn README.md geändert wird)
on:
  push:
    paths:
      - "README.md" # Reagiert nur, wenn README.md geändert wird
  workflow_dispatch: # Ermöglicht manuelle Ausführung

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Repository klonen
      - name: Checkout code
        uses: actions/checkout@v3

      # Schritt 2: Pandoc installieren
      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      # Schritt 3: Markdown in HTML konvertieren
      - name: Convert README.md to test.html
        run: pandoc README.md -o test.html

      # Schritt 4: Änderungen commiten und pushen
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Automated update of test.html"
          git push
